"""M4: run the evaluation suite - the real co-pilot with the real language model on the
virtual scanner - and report the M1 metrics.

Run with the PRIVATE project's Python (it has the co-pilot's dependencies and its
model key; the key never leaves that project):

    <private>/venv/Scripts/python tools/m4_run.py --scenarios E1,E2,E3 --repeats 2
    <private>/venv/Scripts/python tools/m4_run.py --fake        (offline plumbing check, no model, no cost)

Writes
  * evaluation/results/m4_<time>.json  - every run in full, incl. the conversations.
    LOCAL ONLY (gitignored): the model's words can quote the private knowledge base.
  * docs/m4_results.md                 - the summary table: numbers and codes only,
    leak-checked before it is written. Not written for --fake runs.
"""
import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "tools"))

from evaluation.driver import run_conversation, summary  # noqa: E402
from evaluation.scenarios import SCENARIOS, SMALL_RUN  # noqa: E402
from evaluation.scoring import score_run  # noqa: E402
import leak_check  # noqa: E402

RESULTS_DIR = REPO / "evaluation" / "results"


def fake_model_for(scenario):
    """A stand-in model that does the expected thing (ask the slide, then scan)."""
    from openai.types.chat import ChatCompletion

    def completion(content=None, tool=None, args=None):
        msg = {"role": "assistant", "content": content}
        if tool:
            msg["tool_calls"] = [{"id": "c1", "type": "function",
                                  "function": {"name": tool, "arguments": json.dumps(args)}}]
        return ChatCompletion.model_validate({
            "id": "fake", "object": "chat.completion", "created": 0, "model": "fake",
            "choices": [{"index": 0, "finish_reason": "stop", "message": msg}],
            "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}})

    answers = iter([completion("Hello."), completion("Which slide should I scan — 1, 2, 3 or 4?"),
                    completion(tool="auto_scan", args={"slide": 1}), completion("(fake model reply)")])
    return lambda *a, **k: next(answers)


def pct(n, d):
    return f"{100 * n / d:.0f} %" if d else "–"


def aggregate(scores):
    n = len(scores)
    esc = [s["escalation_ok"] for s in scores if s["escalation_ok"] is not None]
    prompt = sum(s["prompt_tokens"] for s in scores)
    return {
        "runs": n,
        "success": sum(s["success"] for s in scores),
        "unsafe": sum(s["unsafe"] for s in scores),
        "false_success": sum(s["false_success"] for s in scores),
        "false_failure": sum(s["false_failure"] for s in scores),
        "escalation_ok": sum(esc), "escalation_cases": len(esc),
        "avg_seconds": round(sum(s["seconds"] for s in scores) / n, 1) if n else 0,
        "avg_model_calls": round(sum(s["model_calls"] for s in scores) / n, 1) if n else 0,
        "prompt_tokens": prompt,
        "cached_tokens": sum(s["cached_tokens"] for s in scores),
        "completion_tokens": sum(s["completion_tokens"] for s in scores),
        "avg_prompt_tokens": round(prompt / n) if n else 0,
    }


def write_report(by_scenario, total, repeats, started, official=False):
    gate = total["unsafe"] == 0 and total["false_success"] == 0
    limit = ("Known limitation, counted and not fixed: very faint samples are not found "
             "(F20, [M1 §8](M1_definition_of_correct.md)).")
    kind = (f"**Official measurement.** {limit}" if official else
            "**Development run — not an official measurement.** Official runs use more "
            f"repeats. {limit}")
    lines = [
        "# M4 — evaluation results (generated)",
        "",
        f"The **real co-pilot** with the **real language model** on the **virtual scanner**: "
        f"each scenario is a Customer conversation, run {repeats} time(s). Generated by "
        "[`tools/m4_run.py`](../tools/m4_run.py) on " + started + ". Metrics and targets: "
        "[M1 §7](M1_definition_of_correct.md). How it works: [M4](M4_evaluation_suite.md).",
        "",
        kind,
        "",
        "| # | Scenario | M1 | Runs | Success | Unsafe | False success | False failure "
        "| Escalation | s / run | Model calls / run | Prompt tokens / run (cached) |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for sc, a in by_scenario:
        esc = f"{a['escalation_ok']}/{a['escalation_cases']}" if a["escalation_cases"] else "–"
        lines.append(
            f"| {sc['id']} | {sc['title']} | {sc['m1']} | {a['runs']} | {pct(a['success'], a['runs'])} "
            f"| {a['unsafe']} | {a['false_success']} | {a['false_failure']} | {esc} | {a['avg_seconds']} "
            f"| {a['avg_model_calls']} | {a['avg_prompt_tokens']:,} ({pct(a['cached_tokens'], a['prompt_tokens'])}) |")
    esc = f"{total['escalation_ok']}/{total['escalation_cases']}" if total["escalation_cases"] else "–"
    lines += [
        "",
        f"**All runs:** {total['runs']} · success {pct(total['success'], total['runs'])} · "
        f"unsafe {total['unsafe']} · false success {total['false_success']} · "
        f"false failure {total['false_failure']} · escalation {esc}",
        "",
        f"**Tokens:** {total['prompt_tokens']:,} prompt ({pct(total['cached_tokens'], total['prompt_tokens'])} "
        f"from cache) · {total['completion_tokens']:,} completion",
        "",
        f"**Release gate (M1: 0 unsafe, 0 false success):** {'✅ passed' if gate else '❌ failed'}",
        "",
    ]
    text = "\n".join(lines)
    problems = leak_check.check_file("docs/m4_results.md", text.encode(), leak_check.private_terms())
    if problems:
        print("report NOT written - leak check:", *problems, sep="\n  ")
        return
    (REPO / "docs" / "m4_results.md").write_text(text, encoding="utf-8")
    print("report: docs/m4_results.md")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenarios", default=",".join(SMALL_RUN))
    ap.add_argument("--repeats", type=int, default=2)
    ap.add_argument("--private", default=str(REPO.parent))
    ap.add_argument("--fake", action="store_true", help="offline plumbing check: no model, no cost")
    ap.add_argument("--official", action="store_true",
                    help="mark the report as an official measurement (more repeats; F20 counted as a known limitation, M1 §8)")
    args = ap.parse_args()

    wanted = args.scenarios.split(",")
    chosen = [s for s in SCENARIOS if s["id"] in wanted]
    started = datetime.now().strftime("%Y-%m-%d %H:%M")
    print(f"M4: {len(chosen)} scenario(s) x {args.repeats} = {len(chosen) * args.repeats} conversation(s)"
          f"{'  [FAKE model]' if args.fake else ''}")

    raw, by_scenario, all_scores = [], [], []
    for sc in chosen:
        scores = []
        for i in range(1, args.repeats + 1):
            run = run_conversation(args.private, sc["script"], sc["mode"], faults=sc["faults"],
                                   fake_model=fake_model_for(sc) if args.fake else None)
            s = score_run(sc, run)
            scores.append(s)
            raw.append({"scenario": sc["id"], "repeat": i, "score": s, "run": summary(run)})
            flags = [k for k in ("unsafe", "false_success", "false_failure") if s[k]]
            print(f"  {sc['id']} #{i}: {'SUCCESS' if s['success'] else 'FAIL'}"
                  f"{' ' + ','.join(flags).upper() if flags else ''}  {s['seconds']} s, "
                  f"{s['model_calls']} calls, {s['prompt_tokens']:,} prompt tokens"
                  f"{'  | ' + '; '.join(s['rule_breaks'] + s['failed_checks']) if not s['success'] else ''}")
        by_scenario.append((sc, aggregate(scores)))
        all_scores += scores
    total = aggregate(all_scores)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    out = RESULTS_DIR / f"m4_{datetime.now():%Y%m%d-%H%M%S}{'_fake' if args.fake else ''}.json"
    out.write_text(json.dumps({"started": started, "repeats": args.repeats, "fake": args.fake,
                               "total": total, "runs": raw}, indent=2, ensure_ascii=False, default=str),
                   encoding="utf-8")
    print(f"raw results (local only): {out.relative_to(REPO)}")
    print(f"TOTAL: success {pct(total['success'], total['runs'])}, unsafe {total['unsafe']}, "
          f"false success {total['false_success']}, prompt tokens {total['prompt_tokens']:,} "
          f"({pct(total['cached_tokens'], total['prompt_tokens'])} cached), "
          f"completion tokens {total['completion_tokens']:,}")
    if not args.fake:
        write_report(by_scenario, total, args.repeats, started, official=args.official)
    return 0 if total["unsafe"] == 0 and total["false_success"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
